language: go
go:
 - 1.x
 - tip

go_import_path: gomodules.xyz/grpc-go-addons

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod

env:
  - GO111MODULE=on

install: true

script:
  - go build ./...
  - ./hack/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
